# Generated by Django 2.2.16 on 2021-09-10 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210910_1244'),
    ]

    operations = [
    ]
